### ISSUE TITLE
move confluence roadmap here

### ISSUE THREAD

**Issue by tschady** [finos/voice-metadata-standard#39]
As agreed to in our last PMC meeting, please move the project roadmap from confluence to this project, wherever it fits best (I suggest the Wiki, with a link from the README).

https://finosfoundation.atlassian.net/wiki/spaces/VOICE/pages/915472519/Voice+Metadata+Roadmap

**Comment by vitorespindola** [comment]
I've made a few changes and published it here:

https://github.com/finos/voice-metadata-standard/wiki#roadmap

**Comment by tschady** [comment]
👍
