### ISSUE TITLE
enum call-types prevent future-proofing.

### ISSUE THREAD

**Issue by tschady** [finos/voice-metadata-standard#8]
A future-proof standard would not exclude future call options by specifying restrictive enum range.
This should just be a string value, not an enum.

Similarly, all text description of call-types should be adjusted to not specify options.

```json
"properties": {
			"callRecordType": {
				"type": "string",
				"enum": [
					"Shoutdown",
					"Ringdown",
					"Dialtone"
				],
				"description": "The type of call that was made (dialtone, ringdown, shoutdown, etc)"
			}, 
```

**Comment by kemmiso** [comment]
Could the issue then could be that different parties start to use different values for the same options?

**Comment by leop-tcto** [comment]
@tschady Could you suggest another way? I like the enum because it is clear and we can add more values to it.

**Comment by tschady** [comment]
n/m, my objection is invalid.  Sorry for the staleness.
